[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "yarn build && echo \"NEXTAUTH_URL=$URL\" > .env.local"

[context.deploy-preview]
  command = "yarn build && echo \"NEXTAUTH_URL=$DEPLOY_PRIME_URL\" > .env.local"
